export const movieList = [
  {
    popularity: 468.811,
    vote_count: 1139,
    video: false,
    poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
    id: 181812,
    adult: false,
    backdrop_path: "/dCB7d4l0mfpsISZvr6aPE2z5QF6.jpg",
    original_language: "en",
    original_title: "Star Wars: The Rise of Skywalker",
    genre_ids: [28, 12, 878],
    title: "Star Wars: The Rise of Skywalker",
    vote_average: 6.7,
    overview:
      "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
    release_date: "2019-12-18"
  },
  {
    popularity: 509.741,
    vote_count: 1468,
    video: false,
    poster_path: "/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg",
    id: 419704,
    adult: false,
    backdrop_path: "/duengnNbJdTdjR329SmAAJO4stC.jpg",
    original_language: "en",
    original_title: "Ad Astra",
    genre_ids: [12, 18, 9648, 878, 53],
    title: "Ad Astra",
    vote_average: 6,
    overview:
      "The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.",
    release_date: "2019-09-17"
  },
  {
    popularity: 260.079,
    vote_count: 6879,
    video: false,
    poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    id: 475557,
    adult: false,
    backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    original_language: "en",
    original_title: "Joker",
    genre_ids: [80, 18, 53],
    title: "Joker",
    vote_average: 8.3,
    overview:
      "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
    release_date: "2019-10-02"
  },
  {
    popularity: 247.518,
    vote_count: 510,
    video: false,
    poster_path: "/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg",
    id: 512200,
    adult: false,
    backdrop_path: "/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg",
    original_language: "en",
    original_title: "Jumanji: The Next Level",
    genre_ids: [28, 12, 35, 14],
    title: "Jumanji: The Next Level",
    vote_average: 6.7,
    overview:
      "As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.",
    release_date: "2019-12-04"
  },
  {
    popularity: 164.977,
    vote_count: 1253,
    video: false,
    poster_path: "/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg",
    id: 330457,
    adult: false,
    backdrop_path: "/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg",
    original_language: "en",
    original_title: "Frozen II",
    genre_ids: [12, 16, 10402, 10751],
    title: "Frozen II",
    vote_average: 7,
    overview:
      "Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.",
    release_date: "2019-11-20"
  },
  {
    popularity: 180.687,
    vote_count: 679,
    video: false,
    poster_path: "/pIcV8XXIIvJCbtPoxF9qHMKdRr2.jpg",
    id: 338967,
    adult: false,
    backdrop_path: "/jCCdt0e8Xe9ttvevD4S3TSMNdH.jpg",
    original_language: "en",
    original_title: "Zombieland: Double Tap",
    genre_ids: [28, 35, 27],
    title: "Zombieland: Double Tap",
    vote_average: 7.1,
    overview:
      "Columbus, Tallahassee, Wichita, and Little Rock move to the American heartland as they face off against evolved zombies, fellow survivors, and the growing pains of the snarky makeshift family.",
    release_date: "2019-10-09"
  },
  {
    popularity: 154.272,
    vote_count: 27,
    video: false,
    poster_path: "/eU0orGizEpOli4wtN8HtfOOJDlA.jpg",
    id: 516700,
    adult: false,
    backdrop_path: "/mlaX4c2M6usnhXHG5sYJcKVXflA.jpg",
    original_language: "id",
    original_title: "Gundala",
    genre_ids: [28, 80, 18],
    title: "Gundala",
    vote_average: 5.8,
    overview:
      "Sancaka has lived on the streets since his parents left him. Living a hard life, Sancaka survives by thinking about his own safety. When the condition of the city gets worse and injustice rages throughout the country, Sancaka must decide whether he continues to live to look after himself or rise to become their oppressed hero.",
    release_date: "2019-08-29"
  },
  {
    popularity: 140.216,
    vote_count: 734,
    video: false,
    poster_path: "/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg",
    id: 509967,
    adult: false,
    backdrop_path: "/eFw5YSorHidsajLTayo1noueIxI.jpg",
    original_language: "en",
    original_title: "6 Underground",
    genre_ids: [28, 35, 53],
    title: "6 Underground",
    vote_average: 6.3,
    overview:
      "After faking his death, a tech billionaire recruits a team of international operatives for a bold and bloody mission to take down a brutal dictator.",
    release_date: "2019-12-13"
  },
  {
    popularity: 118.871,
    vote_count: 64,
    video: false,
    poster_path: "/MBiKqTsouYqAACLYNDadsjhhC0.jpg",
    id: 486589,
    adult: false,
    backdrop_path: "/bga3i5jcejBekr2FCGJga1fYCh.jpg",
    original_language: "en",
    original_title: "Red Shoes and the Seven Dwarfs",
    genre_ids: [16, 10749],
    title: "Red Shoes and the Seven Dwarfs",
    vote_average: 6.2,
    overview:
      "Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.",
    release_date: "2019-07-25"
  },
  {
    popularity: 104.317,
    vote_count: 3424,
    video: false,
    poster_path: "/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
    id: 466272,
    adult: false,
    backdrop_path: "/c6YyKddg8iVDYRRVZLDEd3m22RI.jpg",
    original_language: "en",
    original_title: "Once Upon a Time… in Hollywood",
    genre_ids: [35, 18, 53],
    title: "Once Upon a Time… in Hollywood",
    vote_average: 7.5,
    overview:
      "Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…",
    release_date: "2019-07-25"
  },
  {
    popularity: 74.378,
    vote_count: 9467,
    video: false,
    poster_path: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
    id: 181808,
    adult: false,
    backdrop_path: "/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg",
    original_language: "en",
    original_title: "Star Wars: The Last Jedi",
    genre_ids: [28, 12, 14, 878],
    title: "Star Wars: The Last Jedi",
    vote_average: 7,
    overview:
      "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
    release_date: "2017-12-13"
  },
  {
    popularity: 316.018,
    vote_count: 46,
    video: false,
    poster_path: "/2MwpeDrI7RbgD6bipT31kpMZe9u.jpg",
    id: 449924,
    adult: false,
    backdrop_path: "/ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg",
    original_language: "cn",
    original_title: "葉問4",
    genre_ids: [28, 18, 36],
    title: "Ip Man 4: The Finale",
    vote_average: 6.4,
    overview:
      "Ip Man 4 is an upcoming Hong Kong biographical martial arts film directed by Wilson Yip and produced by Raymond Wong. It is the fourth in the Ip Man film series based on the life of the Wing Chun grandmaster of the same name and features Donnie Yen reprising the role. The film began production in April 2018 and ended in July the same year.",
    release_date: "2019-12-20"
  },
  {
    popularity: 94.063,
    vote_count: 94,
    video: false,
    poster_path: "/84Xz2Jh60tC3ICO1CY27wc0zwgC.jpg",
    id: 461130,
    adult: false,
    backdrop_path: "/raspMdRYIj0cCF6SQH8NQ1lLLMB.jpg",
    original_language: "en",
    original_title: "Code 8",
    genre_ids: [28, 80, 18, 878, 53],
    title: "Code 8",
    vote_average: 6.3,
    overview:
      "In Lincoln City, some inhabitants have extraordinary abilities. Most live below the poverty line, under the close surveillance of a heavily militarized police force. Connor, a construction worker with powers, involves with a criminal gang to help his ailing mother. (Based on the short film “Code 8,” 2016.)",
    release_date: "2019-12-06"
  },
  {
    popularity: 93.799,
    vote_count: 16,
    video: false,
    poster_path: "/30YacPAcxpNemhhwX0PVUl9pVA3.jpg",
    id: 431693,
    adult: false,
    backdrop_path: "/nZ1N5tDpoNm8UJBmWGoTZCRiDoQ.jpg",
    original_language: "en",
    original_title: "Spies in Disguise",
    genre_ids: [28, 12, 16, 35],
    title: "Spies in Disguise",
    vote_average: 8.1,
    overview:
      "When the world's best spy is turned into a pigeon, he must rely on his nerdy tech officer to save the world.",
    release_date: "2019-12-24"
  },
  {
    popularity: 75.494,
    vote_count: 16118,
    video: false,
    poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    id: 299536,
    adult: false,
    backdrop_path: "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
    original_language: "en",
    original_title: "Avengers: Infinity War",
    genre_ids: [28, 12, 878],
    title: "Avengers: Infinity War",
    vote_average: 8.3,
    overview:
      "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    release_date: "2018-04-25"
  },
  {
    popularity: 77.953,
    vote_count: 871,
    video: false,
    poster_path: "/kTQ3J8oTTKofAVLYnds2cHUz9KO.jpg",
    id: 522938,
    adult: false,
    backdrop_path: "/spYx9XQFODuqEVoPpvaJI1ksAVt.jpg",
    original_language: "en",
    original_title: "Rambo: Last Blood",
    genre_ids: [28, 18, 53],
    title: "Rambo: Last Blood",
    vote_average: 5.9,
    overview:
      "After fighting his demons for decades, John Rambo now lives in peace on his family ranch in Arizona, but his rest is interrupted when Gabriela, the granddaughter of his housekeeper María, disappears after crossing the border into Mexico to meet her biological father. Rambo, who has become a true father figure for Gabriela over the years, undertakes a desperate and dangerous journey to find her.",
    release_date: "2019-09-19"
  },
  {
    popularity: 87.178,
    vote_count: 104,
    video: false,
    poster_path: "/4E2lyUGLEr3yH4q6kJxPkQUhX7n.jpg",
    id: 568012,
    adult: false,
    backdrop_path: "/iGnCzXEx0cFlUbpyAMeHwHWhPhx.jpg",
    original_language: "ja",
    original_title: "ワンピーススタンピード",
    genre_ids: [28, 12, 16],
    title: "One Piece: Stampede",
    vote_average: 7.4,
    overview:
      "One Piece: Stampede is a stand-alone film that celebrates the anime's 20th Anniversary and takes place outside the canon of the \"One Piece\" TV series. Monkey D. Luffy and his Straw Hat pirate crew are invited to a massive Pirate Festival that brings many of the most iconic characters from throughout the franchise to participate in competition with the Straw Hats to find Roger's treasure. It also pits the Straw Hats against a new enemy named Bullet, a former member of Roger's crew.",
    release_date: "2019-08-09"
  },
  {
    popularity: 67.08,
    vote_count: 38,
    video: false,
    poster_path: "/9zvjgr1v8pwFYQNHZTtnKNQUWmw.jpg",
    id: 536869,
    adult: false,
    backdrop_path: "/kKGYGXu1lOVxY8XejQ3lAyV5QXZ.jpg",
    original_language: "en",
    original_title: "Cats",
    genre_ids: [35, 18, 14, 10402],
    title: "Cats",
    vote_average: 5.3,
    overview:
      "A tribe of cats called the Jellicles must decide yearly which one will ascend to the Heaviside Layer and come back to a new Jellicle life.",
    release_date: "2019-12-19"
  },
  {
    popularity: 81.607,
    vote_count: 853,
    video: false,
    poster_path: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    id: 546554,
    adult: false,
    backdrop_path: "/AbRYlvwAKHs0YuyNO6NX9ofq4l6.jpg",
    original_language: "en",
    original_title: "Knives Out",
    genre_ids: [35, 9648, 53],
    title: "Knives Out",
    vote_average: 7.9,
    overview:
      "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
    release_date: "2019-11-27"
  },
  {
    popularity: 56.782,
    vote_count: 13434,
    video: false,
    poster_path: "/weUSwMdQIa3NaXVzwUoIIcAi85d.jpg",
    id: 140607,
    adult: false,
    backdrop_path: "/c2Ax8Rox5g6CneChwy1gmu4UbSb.jpg",
    original_language: "en",
    original_title: "Star Wars: The Force Awakens",
    genre_ids: [28, 12, 14, 878],
    title: "Star Wars: The Force Awakens",
    vote_average: 7.4,
    overview:
      "Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.",
    release_date: "2015-12-15"
  }
];
