version: "3.7"
services:
  db:
    image: postgres:11
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      # POSTGRES_DB: stripe-example
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
  web:
    build: .
    container_name: server_container
    volumes:
      - .:/usr/app
    depends_on:
      - db
    ports:
      - "4000:4000"
volumes:
  pg_data:
